replicaCount: 1

image:
  registry: "ghcr.io"
  repository: "bergshrund"
  tag: "latest"
  pullPolicy: Always
imagePullSecrets: []

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: "controller-sa"

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  # capabilities:
  #   drop:
  #   - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  # runAsUser: 1000

service:
  type: LoadBalancer
  port: 8080

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Additional volumes on the output Deployment definition.
volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
