name: k8s-controller ci/cd

on:
    pull_request:
        branches: [ "main" ]
        paths-ignore:
          - 'helm/**'
          - '.github/workflows/**'
          - 'README.md'
    push:
        branches: [ "main" ]
        paths-ignore:
          - 'helm/**'
          - '.github/workflows/**'
          - 'README.md'
        tags: [ 'v*.*.*' ]
        
    workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: k8s-controller
  CHART_NAME: k8s-controller
  TARGETOS: linux
  TARGETARCH: amd64

jobs:
    ci:
        name: CI
        runs-on: ubuntu-latest
        permissions:
          contents: read
          packages: write
        steps:
          - name: Checkout
            uses: actions/checkout@v4
            with:
              fetch-depth: 0
          - name: Set up Go
            uses: actions/setup-go@v5
            with:
                go-version: '1.21.3'
          - name: Set version      
            id: vars
            run: |
              if [[ $GITHUB_REF == refs/tags/* ]]; then
                VERSION=${GITHUB_REF#refs/tags/}
                APP_VERSION=${VERSION}
                DOCKER_TAG=${VERSION}
              else
                SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
                VERSION="0.1.0+${GITHUB_SHA}"
                APP_VERSION=${GITHUB_SHA}
                DOCKER_TAG="0.1.0-${SHORT_SHA}"
              fi
              echo "version=$VERSION" >> $GITHUB_OUTPUT
              echo "app_version=$APP_VERSION" >> $GITHUB_OUTPUT
              echo "docker_tag=$DOCKER_TAG" >> $GITHUB_OUTPUT
          - name: Build
            run: make build
          - name: Test
            run: make test

          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3
          - name: Log in to GHCR
            uses: docker/login-action@v3
            with:
              registry: ${{ env.REGISTRY }} 
              username: ${{ github.actor }}
              password: ${{ secrets.GITHUB_TOKEN }}
          
          - name: Build Docker image # github.repository variable has <account>/<repo> form
            run: TARGETOS=${{ env.TARGETOS }} TARGETARCH=${{ env.TARGETARCH }} REGISTRY=${{ env.REGISTRY }}/${{ github.repository }} VERSION=${{ steps.vars.outputs.docker_tag }} make docker-build
          
          - name: Trivy Scan
            uses: aquasecurity/trivy-action@0.28.0
            with:
              image-ref: ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.docker_tag }}-${{ env.TARGETOS }}-${{ env.TARGETARCH }}
          
          - name: Push Docker image
            run: docker push ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.docker_tag }}-${{ env.TARGETOS }}-${{ env.TARGETARCH }}
          
          - name: Read chart version from Chart.yaml
            uses: mikefarah/yq@master
            with:
              cmd: echo "CHART_VERSION=$(yq '.version' helm/k8s-controller/Chart.yaml)" >> $GITHUB_ENV

          - name: Update image tag in values.yaml
            uses: mikefarah/yq@master
            env:
              DOCKER_TAG: ${{ steps.vars.outputs.docker_tag }}-${{ env.TARGETOS }}-${{ env.TARGETARCH }}
            with:
              cmd: yq -i '.image.tag=strenv(DOCKER_TAG)' helm/k8s-controller/values.yaml
          
          - name: Update Helm Chart appVersion
            uses: mikefarah/yq@master
            env:
              APP_VERSION: ${{ steps.vars.outputs.app_version }}
            with:
              cmd: yq -i '.appVersion=strenv(APP_VERSION)' helm/k8s-controller/Chart.yaml

          - name: Checkout private action repo
            uses: actions/checkout@v4
            with:
              repository: bergshrund/semver-action
              token: ${{ secrets.SEMVER_ACTION_PAT }}
              path: .github/actions/semver-action

          - name: Autoincrement current helm chart version
            id: semver-action
            if: github.ref == 'refs/tags/*'
            uses: ./github/actions/semver-action
            with:
              semver: ${{ env.CHART_VERSION }}

          - name: Update Helm Chart version
            if: github.ref == 'refs/tags/*'
            uses: mikefarah/yq@master
            env:
              CHART_VERSION: ${{ steps.semver-action.outputs.version }} 
            with:
              cmd: yq -i '.version="${{ steps.semver-action.outputs.version }}"' helm/k8s-controller/Chart.yaml

          - run: |
                git config user.name github-actions
                git config user.email github-actions@users.noreply.github.com
                git commit -am "Update Helm chart version: ${CHART_VERSION} appVersion: ${APP_VERSION}"
                git push origin main

          - name: Package Helm chart
            run: |
              helm package helm/k8s-controller --version ${{ env.CHART_VERSION }}
              mkdir -p chart-artifacts
              mv k8s-controller-${{ env.CHART_VERSION }}.tgz chart-artifacts/

          - name: Upload Helm chart artifact
            uses: actions/upload-artifact@v4
            with:
              name: helm-chart
              path: chart-artifacts/ 